ZSH_THEME="af-magic"
DISABLE_MAGIC_FUNCTIONS="true"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=245"
export BROWSER=/usr/bin/google-chrome-stable
export EDITOR=/usr/bin/vim
export PAGER=/usr/bin/bat
export TERMINAL=/usr/bin/kitty
export VISUAL=/usr/bin/eog
source $ZSH/oh-my-zsh.sh
export PATH=$PATH:~/.pdtm/go/bin
source /opt/skillarch/dotfiles/aliases
eval "$(register-python-argcomplete --no-defaults exegol)"