misconfigurations:
  - id: AVD-DS-0002 # docker: use of root user
  - id: AVD-DS-0025 # docker: lack of no-cache
  - id: AVD-DS-0010 # docker: run with sudo
  - id: AVD-DS-0029 # docker: lack of norecommends
  - id: AVD-DS-0019 # docker: lack of dnf clean all
  - id: AVD-DS-0022 # docker: deprecated maintainer

secrets:
  - id: aws-access-key-id
    paths:
      - /home/hacker/.local/share/pipx/venvs/yt-dlp/lib/python3.14/site-packages/yt_dlp/extractor/shahid.py
