FROM cachyos/cachyos:latest

# Create hacker user and group, set password and configure sudo
RUN groupadd hacker && \
    useradd -m -g hacker -s /bin/bash hacker && \
    echo "hacker:offenskill" | chpasswd && \
    echo "hacker ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/hacker

# Add skillarch
COPY . /opt/skillarch
RUN chown -R hacker:hacker /opt/skillarch
USER hacker
ENV USER=hacker
ENV TZ=UTC
ENV LC_ALL=C
WORKDIR /opt/skillarch

# Install skillarch
RUN make install-base
RUN make install-cli-tools
RUN make install-shell
RUN make install-offensive
RUN make test-lite
RUN make clean

# Remove NOPASSWD capability after installation
USER root
RUN echo "hacker ALL=(ALL) ALL" > /etc/sudoers.d/hacker

# Final setup
USER hacker
WORKDIR /home/hacker
ENTRYPOINT ["/bin/zsh", "-il"]
