FROM thelaluka/skillarch:lite

USER root
echo "hacker ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/hacker

USER hacker
WORKDIR /opt/skillarch

# Install skillarch
RUN make install-docker
RUN make install-gui
RUN make install-gui-tools
RUN make install-wordlists
RUN make install-hardening
RUN make install-tweaks

# Remove NOPASSWD capability after installation
USER root
RUN echo "hacker ALL=(ALL) ALL" > /etc/sudoers.d/hacker

# Final setup
USER hacker
WORKDIR /home/hacker
ENTRYPOINT ["/bin/zsh", "-il"]
