desktop:
  resolution:
    width: 1920
    height: 1080
  allow_resize: true
network:
  protocol: http
  websocket_port: 8443
  interface: 127.0.0.1
  ssl:
    pem_certificate: /home/hacker/.vnc/self.pem
    pem_key: /home/hacker/.vnc/self.key
